[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -O2                 
    -DCORE_DEBUG_LEVEL=5  

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit BMP085 Library
    adafruit/Adafruit BusIO
    chris--a/Keypad