DROP TABLE IF EXISTS AUDITLOG;
DROP TABLE IF EXISTS SESSIONS;
DROP TABLE IF EXISTS ALERTS;
DROP TABLE IF EXISTS SENSORSREADING;
DROP TABLE IF EXISTS SENSORS;
DROP TABLE IF EXISTS DEVICES;
DROP TABLE IF EXISTS USERS;
