SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE USERS;
TRUNCATE TABLE DEVICES;
TRUNCATE TABLE SENSORS;
TRUNCATE TABLE SENSORSREADING;
TRUNCATE TABLE ALERTS;
TRUNCATE TABLE AUDITLOG;
TRUNCATE TABLE SESSIONS;

SET FOREIGN_KEY_CHECKS = 1;